[project]
name = "repl-nix-workspace"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.13"
dependencies = [
    "boto3>=1.40",
    "fastapi>=0.141.1",
    "httpx>=0.28.1",
    "pillow>=12.3.0",
    "psycopg[binary]>=3.3.6",
    "pyjwt[crypto]>=2.14.0",
    "pytest>=9.1.1",
    "python-multipart>=0.0.32",
    "sqlalchemy>=2.0.54",
    "uvicorn>=0.53.0",
]

[dependency-groups]
dev = [
    "moto[s3]>=5",
]
